### ISSUE TITLE
No more daily solar production

### ISSUE THREAD

**Issue by gieljnssns** [smappee/pysmappee#1]
I had the same error like this https://github.com/home-assistant/core/issues/37296#issuecomment-652988487
Now I've updated to the last version (custom_component), now I have 66 entity's, but no more solar production...
<img width="1251" alt="Schermafbeelding 2020-07-02 om 15 02 52" src="https://user-images.githubusercontent.com/17234951/86362135-1c499000-bc75-11ea-87c0-8915679319ac.png">
This are the only sensors

**Comment by bsmappee** [comment]
Nice catch! Thank you for opening this issue. We have immediately fixed this with commit [#672ab8a](https://github.com/smappee/pysmappee/commit/672ab8ae2bffcc282e63ef8c776ec20952e89a91) and will bump the dependency version in the Home Assistant integration. There will be 3 solar sensors available again very soon (live production, today, current hour).

**Comment by gieljnssns** [comment]
<img width="1230" alt="Schermafbeelding 2020-07-02 om 15 41 48" src="https://user-images.githubusercontent.com/17234951/86366002-8e70a380-bc7a-11ea-8c5e-e3ad392c5bc8.png">
Thanks a lot now 69 entity's

**Comment by bsmappee** [comment]
We should probably hide the 6 voltage entities as they are unavailable for Smappee Energy and Smappee Solar devices. But still makes 63 entities though.

**Comment by gieljnssns** [comment]
That's fine by me

`sensor.thuis_total_consumption_reactive_power` is also `unknown`

**Comment by gieljnssns** [comment]
I have voltage etc via MQTT 

Btw ```http://192.168.xx.xx/smappee.html``` doesn't work anymore

**Comment by gieljnssns** [comment]
> Btw http://192.168.xx.xx/smappee.html doesn't work anymore

Magic - it's back

**Comment by bsmappee** [comment]
> Btw http://192.168.xx.xx/smappee.html doesn't work anymore

We will never remove that page

**Comment by bsmappee** [comment]
> `sensor.thuis_total_consumption_reactive_power` is also `unknown`

Indeed, live reactive should be a local MQTT only entity.

**Comment by gieljnssns** [comment]
Thanks for your effort!
