### ISSUE TITLE
pysmappee should not try to install the 'test' package

### ISSUE THREAD

**Issue by onkelbeh** [smappee/pysmappee#5]
Hi,

hope you don't mind that I use your component in [Home Assistant Gentoo Overlay](https://github.com/onkelbeh/HomeAssistantRepository).

Component: https://github.com/onkelbeh/HomeAssistantRepository/tree/master/dev-python/pysmappee

During some compile tests I saw that pysmappee tries to install 'test' package at top level, this is fobidden in Gentoo (and most other Distri's). This could easily be fixed with a small change to setup.py:

For now, I added a small `sed` script to my ebuilds:

```bash
src_prepare() {
    sed "s/packages=find_packages()/packages=find_packages(exclude=['tests','tests.*'])/g" -i setup.py || die
    eapply_user
}
```
Sorry, for not posting a build log, I fixed this in my repo a few days ago.
I'll send a pull request in a few seconds.

Thanks a lot.
Please drop me a not when it's fixed, so I can remove the patch.

 \B.

**Comment by bsmappee** [comment]
@onkelbeh PR has been merged
